version: '3.8'

services:
  flask-portfolio:
    image: flaskportfolio:latest
    ports:
      - "8080:80"
    command: ["pipenv", "run", "flask", "--debug", "--app", "api/index.py", "run", "--host=0.0.0.0", "--port=80", "--reload"]
    volumes:
      - .:/flask-portfolio

      
    # environment:
    #   - FLASK_ENV=development